.github/workflows/ci-ai-review.yaml
https://github.com/pex-dev/task-canvas/issues/#{issue_no}
-
1.
=> add: Implementing CodeRabbit CI to implement an AI review function for PR

.github/labeler.yaml, .github/workflows/auto-labeler.yaml
https://github.com/pex-dev/task-canvas/issues/#{issue_no}
-
1.
=> add: auto labeler

frontend/codegen.yaml, frontend/package-lock.json, frontend/package.json, frontend/src/app/_components/AuthorizedApolloProvider.tsx, frontend/src/app/api/query.ts, frontend/src/app/layout.tsx
=> frontendにgraphqlを導入

frontend/codegen.yaml, frontend/graphql.schema.json, frontend/src/generated/graphql.tsx
=> GraphQLのスキーマからTypeScriptの型生成

.github/workflows/ci-lint.yaml, .github/workflows/ci-next-build.yaml, .github/workflows/ci-storybook-build.yaml
=> fix: workflows executed triger

frontend/src/_components/atoms/Input/index.stories.ts, frontend/src/_components/atoms/Input/index.tsx, frontend/src/_components/mui/Input/index.stories.ts, frontend/src/_components/mui/Input/index.tsx, frontend/src/_components/mui/TextField/index.stories.ts, frontend/src/_components/mui/TextField/index.tsx, frontend/src/app/page.tsx
=> Input componentの追加

frontend/.storybook/main.ts, frontend/src/_components/atoms/Input/index.tsx, frontend/src/_components/molecules/Title/index.stories.ts, frontend/src/_components/molecules/Title/index.tsx, frontend/src/app/page.tsx
=> タイトルをページに追加

frontend/src/app/page.tsx
=> fix: page.tsx

Makefile, backend/app/database/seeds/0_todo.sql, docker-compose.yaml
=> DBのSeedのsqlを追加

backend/Dockerfile, docker-compose.yaml
=> update: golang hotreload

frontend/package-lock.json, frontend/package.json
=> パッケージマネージャの更新

frontend/package-lock.json
=> update: package-lock

frontend/package-lock.json
=> フロントのモジュール依存の解消

frontend/package-lock.json, frontend/package.json
=> Muiのバージョンアップ

backend/domain/password.go, backend/domain/password_test.go, backend/domain/user_jwt_token_test.go, backend/driver/generated/querier.go, backend/driver/generated/query.sql.go, backend/driver/sqlc/query.sql, backend/gateway/user_gateway.go, backend/main.go, backend/mock/driver/db_driver.go, backend/mock/port/user_port.go, backend/port/user_port.go, backend/rest/signin.go, backend/rest/todos.go, backend/useCase/generate_jwt.go, backend/useCase/sigin_in.go, backend/useCase/sigin_in_test.go
=> サインイン・JWTをレスポンスヘッダーに返すようにする

backend/main.go, backend/middleware/generate_jwt.go, backend/middleware/validate_jwt.go, backend/rest/todos.go
=> レスポンス時にJWTを付与するmiddlewareを追加

backend/main.go, backend/rest/veryfy_token.go
=> 認証チェックのエンドポイントの追加

frontend/src/app/layout.tsx, frontend/src/driver/index.ts, frontend/src/middleware.ts
=> フロントエンドのmiddlewareの実装

backend/domain/todo.go, backend/driver/generated/querier.go, backend/driver/generated/query.sql.go, backend/driver/sqlc/query.sql, backend/gateway/todo_gateway.go, backend/gateway/todo_gateway_test.go, backend/mock/driver/db_driver.go, backend/mock/port/todo_port.go, backend/port/todo_port.go, backend/rest/todos.go, backend/useCase/delete_todo_usecase.go, backend/useCase/delete_todo_usecase_test.go, backend/useCase/get_todo_usecase.go, backend/useCase/get_todo_usecase_test.go, backend/useCase/store_todo_usecase.go, backend/useCase/store_todo_usecase_test.go, backend/useCase/update_todo_usecase_test.go
=> TODO操作がユーザーに紐づくようにする

frontend/package-lock.json, frontend/package.json
=> update: storybook dependencies

.github/workflows/ci-lint.yaml
=> add: front test ci

.github/workflows/ci-backend-e2e.yaml, .github/workflows/ci-web-e2e.yaml
=> API E2Eの修正によって生じたCIの修正

.github/workflows/ci-backend-e2e.yaml, .github/workflows/ci-web-e2e.yaml
=> fix workflow
